name: CI with GitHub Actions using Maven and JUnit | © 2022 by giao.lang

# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

on:
  push:
    branches: [ main ] # Lấy code từ nhánh main nếu có ai push code lên  
  pull_request:
    branches: [ main ] # Lấy code từ nhánh main nếu có ai gửi pull request  

jobs: # Những công việc dev làm thường ngày: lấy code, build, chạy test, đóng gói, gửi build...
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository # Lấy code từ kho thảy vào máy ảo của GitHub chuẩn bị build ở bước sau
        uses: actions/checkout@v3

      - name: Set up JDK 18 
        uses: actions/setup-java@v3 # Khai báo cần dùng JDK để build
        with:
          java-version: '18' # Khai báo sử dụng phiên bản JDK 18 để build
          distribution: 'temurin'
     
      - name: Build project with Maven
        run: mvn clean package # Maven sẽ dùng file pom.xml để build và đóng gói project
      
      - name: Distribute jar file # Gửi file .jar đi đâu, CD nhảy vào ...
        run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar sau khi build      
     
      - name: Make hyperlink to jar file # Tạo hyperlink để download build 
        uses: actions/upload-artifact@v2
        with:
          name: 1.0-SNAPSHOT.jar # Bản build được đánh version 1.0-SNAPSHOT
          path: staging

# End of CI workflow file
